# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-22 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longName', models.CharField(max_length=200)),
                ('productId', models.CharField(max_length=20)),
                ('storeNums', models.CharField(max_length=20)),
                ('specifics', models.CharField(max_length=20)),
                ('sort', models.CharField(max_length=20)),
                ('marketPrice', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('categoryId', models.CharField(max_length=20)),
                ('childId', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=100)),
                ('brandId', models.CharField(max_length=20)),
                ('brandName', models.CharField(max_length=100)),
                ('safeDay', models.CharField(max_length=20)),
                ('safeUnit', models.CharField(max_length=20)),
                ('safeUnitDesc', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=150)),
                ('sort', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'slideshows',
                'ordering': ['sort'],
            },
        ),
    ]
