# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-22 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.CharField(max_length=20)),
                ('categoryName', models.CharField(max_length=40)),
                ('img', models.CharField(max_length=200)),
                ('sort', models.CharField(max_length=20)),
                ('product1', models.CharField(max_length=20)),
                ('product2', models.CharField(max_length=20)),
                ('product3', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mainDecriptions',
                'ordering': ['sort'],
            },
        ),
    ]
